/* Generated By:JavaCC: Do not edit this line. Token.java Version 4.1 */
/**
 * This file contains the code for JavaCCParser generated
 * by JavaCCParser itself.
 */

package org.javacc.parser;

/** Describes the input token stream. */
public class Token {
  public static class GTToken extends Token {
    public GTToken(int kind, int begin, int end, String image) {
      super(kind, begin, end, image);
    }

    int realKind = JavaCCConstants.GT;
  }

  private int kind;
  private final int begin;
  private final int end;
  private int beginLine;
  private int beginColumn;
  private int endLine;
  private int endColumn;
  private String image;
  /**
   * A reference to the next regular (non-special) token from the input
   * stream.  If this is the last token from the input stream, or if the
   * scanner has not read tokens beyond this one, this field is
   * set to null.  This is true only if this token is also a regular
   * token.  Otherwise, see below for a description of the contents of
   * this field.
   */
  public Token next;
  /**
   * This field is used to access special tokens that occur prior to this
   * token, but after the immediately preceding regular (non-special) token.
   * If there are no such special tokens, this field is set to null.
   * When there are more than one such special token, this field refers
   * to the last of these special tokens, which in turn refers to the next
   * previous special token through its specialToken field, and so on
   * until the first special token (whose specialToken field is null).
   * The next fields of special tokens refer to other special tokens that
   * immediately follow it (without an intervening regular token).  If there
   * is no such token, this field is null.
   */
  public Token specialToken;

  public Token(int kind, int begin, int end, String image) {
    if (begin > end) { throw new IllegalArgumentException(); }
    this.kind = kind;
    this.begin = begin;
    this.end = end;
    this.image = image;
  }

  /** @return Token kind. */
  public int getKind() {
    return kind;
  }

  /** @param kind New token kind. */
  public void setKind(int kind) {
    this.kind = kind;
  }

  /** @return Token image. */
  public String getImage() {
    return image;
  }

  /** @param image New token image. */
  public void setImage(String image) {
    this.image = image;
  }

  /** @return Index of the first character of the token, inclusive. */
  public int getBegin() {
    return begin;
  }

  /** @return Index of the last character of the token, exclusive. */
  public int getEnd() {
    return end;
  }

  /** @return The line number of the first character of this token. */
  public int getBeginLine() {
    return beginLine;
  }

  /** @return The column number of the first character of this token. */
  public int getBeginColumn() {
    return beginColumn;
  }

  /** @return The line number of the last character of this token. */
  public int getEndLine() {
    return endLine;
  }

  /** @return The column number of the last character of this token. */
  public int getEndColumn() {
    return endColumn;
  }

  /**
   * Set token line and column numbers.
   *
   * @param beginLine   The line number of the first character of this token
   * @param beginColumn The column number of the first character of this token.
   * @param endLine     The line number of the last character of this token.
   * @param endColumn   The column number of the last character of this token.
   */
  public void setLineColumn(int beginLine, int beginColumn, int endLine, int endColumn) {
    this.beginLine = beginLine;
    this.beginColumn = beginColumn;
    this.endLine = endLine;
    this.endColumn = endColumn;
  }

  /** @return The image. */
  public String toString() {
    return image;
  }

  public static Token newToken(int kind, int begin, int end, String image) {
    switch (kind) {
      case JavaCCConstants.RUNSIGNEDSHIFT:
      case JavaCCConstants.RSIGNEDSHIFT:
      case JavaCCConstants.GT:
        return new GTToken(kind, begin, end, image);
      default:
        return new Token(kind, begin, end, image);
    }
  }
}
